centreon_application_find_host_templates:
  methods: GET
  path: /configuration/hosts/groups
  controller: 'Centreon\Application\Controller\HostGroupsController::findHostGroups'
  condition: "request.attributes.get('version.is_beta') == true"